### ISSUE TITLE
Glitchy stream, bad webcam?

### ISSUE THREAD

**Issue by ugjka** [nola-a/mjpeg2http#3]
I got some aliexpress webcam that was given away for free to me. It works but, I guess, it produces some borked frames periodically. It is visible in Firefox as white half frame glitches, in Chromium the stream crashes and in VLC it produces tearing.

Here is a screen capture of it happening https://www.youtube.com/watch?v=RIIkCEs4_Rw

Here is a stream dump https://ugjka.net/download/dump.mjpeg

I wonder what can be done about this?

The setup here is an Orange Pi Zero with my cam, a reverse SSH tunnel to my VPS where an Nginx reverse proxy exposes the stream to the world.

**Comment by nolasoft** [comment]
if you have enough space in your orange pi i could prepare a patch to dump directly frames into the disk and so we can check what your webcam is producing.

**Comment by ugjka** [comment]
I have 12GB of free space, I guess, go ahead

**Comment by nolasoft** [comment]
So this is what we are going to do:

- generate jpeg images
- create video: ffmpeg -start_number n -i test_%d.jpg -vcodec mpeg4 test.avi
- play it to check if glitchs are still there

**Comment by ugjka** [comment]
Sounds good, how do i generate the images?

**Comment by nolasoft** [comment]
i am preparing a branch.

**Comment by nolasoft** [comment]
```
$ mkdir /tmp/frames
$ git checkout -b dump-to-file origin/dump-to-file
```

run for a while, and then execute ffmpeg to build video

**Comment by ugjka** [comment]
Borked jpegs https://ugjka.net/download/borkybork/
Fmpeg video https://ugjka.net/download/borkybork.webm

```
Driver Info:
	Driver name      : uvcvideo
	Card type        : GENERAL - UVC : GENERAL - UVC 
	Bus info         : usb-1c1b400.usb-1
	Driver version   : 5.10.60
	Capabilities     : 0x84a00001
		Video Capture
		Metadata Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
Media Driver Info:
	Driver name      : uvcvideo
	Model            : GENERAL - UVC : GENERAL - UVC 
	Serial           : 
	Bus info         : usb-1c1b400.usb-1
	Media version    : 5.10.60
	Hardware revision: 0x00000100 (256)
	Driver version   : 5.10.60
Interface Info:
	ID               : 0x03000002
	Type             : V4L Video
Entity Info:
	ID               : 0x00000001 (1)
	Name             : GENERAL - UVC : GENERAL - UVC 
	Function         : V4L2 I/O
	Flags         : default
	Pad 0x01000007   : 0: Sink
	  Link 0x02000010: from remote pad 0x100000a of entity 'Processing 5': Data, Enabled, Immutable
Priority: 2
Video input : 0 (Camera 1: ok)
Format Video Capture:
	Width/Height      : 640/480
	Pixel Format      : 'MJPG' (Motion-JPEG)
	Field             : None
	Bytes per Line    : 0
	Size Image        : 960000
	Colorspace        : Default
	Transfer Function : Default (maps to Rec. 709)
	YCbCr/HSV Encoding: Default (maps to ITU-R 601)
	Quantization      : Default (maps to Full Range)
	Flags             : 
Crop Capability Video Capture:
	Bounds      : Left 0, Top 0, Width 640, Height 480
	Default     : Left 0, Top 0, Width 640, Height 480
	Pixel Aspect: 1/1
Selection Video Capture: crop_default, Left 0, Top 0, Width 640, Height 480, Flags: 
Selection Video Capture: crop_bounds, Left 0, Top 0, Width 640, Height 480, Flags: 
Streaming Parameters Video Capture:
	Capabilities     : timeperframe
	Frames per second: 30.000 (30/1)
	Read buffers     : 0
```

**Comment by nolasoft** [comment]
ok,  so  i'd say the issue is in webcam/driver

**Comment by ugjka** [comment]
Ok, thank you for your time, I'm closing this now and gonna get a better webcam :)
